baseURL = "https://khigasa.github.io/higs"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "|-|-|-| HaggardHigs'Hacks - とある物理屋(になりたい人)の回想"
canonifyurls = true
publishdir = "public"
theme="hugo-tranquilpeak-theme"
googleAnalytics = "UA-128672321-2"
disqusShortname = "haggard-higs-hacks"
paginate = 7

[permalinks]
  post = "/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "kHigasa"
  bio = "Coding in C/C++ & Python is my basic skill set."
  job = "Bachelor of science in physics"
  location = "Tokyo, Japan"
  gravatarEmail = "kojihigasa@gmail.com"
  twitter = "andreHiGasa"

[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
  url = "/page/about"
[[menu.main]]
  weight = 3
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
  url = "/categories"
[[menu.main]]
  weight = 4
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
  url = "/tags"
[[menu.main]]
  weight = 5
  identifier = "search"
  name = "Search"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-search\"></i>"
  url = "/page/search"
  class = "st-search-show-outputs"
[[menu.main]]
  weight = 6
  identifier = "archives"
  name = "Archives"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
  url = "/archives"
[[menu.main]]
  weight = 7
  identifier = "contact"
  name = "Contact"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-envelope\"></i>"
  url = "/page/contact"

[[menu.links]]
  weight = 1
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/kHigasa"
[[menu.links]]
  weight = 2
  identifier = "kaggle"
  name = "Kaggle"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-font\"></i>"
  url = "https://www.kaggle.com/khigasa"
[[menu.links]]
  weight = 3
  identifier = "codeforces"
  name = "Codeforces"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-birthday-cake\"></i>"
  url = "https://codeforces.com/profile/khigasa"
[[menu.links]]
  weight = 4
  identifier = "ctf"
  name = "CTF"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-flag-checkered\"></i>"
  url = "https://pwnable.tw/user/15978"
[[menu.links]]
  weight = 5
  identifier = "stackoverflow"
  name = "Stack Overflow"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-stack-overflow\"></i>"
  url = "https://stackoverflow.com/users/9315234/koji-higasa"
[[menu.links]]
  weight = 6
  identifier = "twitter"
  name = "Twitter"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-twitter\"></i>"
  url = "https://twitter.com/andreHiGasa"
[[menu.links]]
  weight = 7
  identifier = "facebook"
  name = "Facebook"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-facebook\"></i>"
  url = "https://www.facebook.com/khigasa"

[[menu.misc]]
  weight = 0
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
  url = "/index.xml"

[params]
  author = "kHigasa"
  description = "HHH HaggardHigs'Hacks - とある物理屋(になりたい人)の回想"
  sidebarBehavior = 1
  thumbnailImage = true
  thumbnailImagePosition = "right"
  autoThumbnailImage = true
  coverImage = "cover-v1.2.0.jpg"
  imageGallery = true
  hierarchicalCategories = true
  syntaxHighlighter = 'highlight.js'
  wapPaginator = true

  [[params.sharingOptions]]
    name = "Facebook"
    icon = "fa-facebook-official"
    url = "https://www.facebook.com/sharer/sharer.php?u=%s"

  [[params.sharingOptions]]
    name = "Twitter"
    icon = "fa-twitter"
    url = "https://twitter.com/intent/tweet?text=%s"

[blackfriday]
  hrefTargetBlank = true
