baseURL = "https://khigasa.github.io/higs"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "|-|-|-| Haggard Higs' Hacks"
canonifyurls = true
publishdir = "docs"
theme="hugo-tranquilpeak-theme"
googleAnalytics = "UA-128672321-2"
disqusShortname = "haggard-higs-hacks"
paginate = 10

[language]
[language.en]
[language.ja]

[permalinks]
  post = "/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "kHigasa"
  bio = "Coding in C/C++ & Julia is my basic skill set."
  job = "Bachelor of Science in Physics"
  location = "Tokyo, Japan"
  picture = "images/avatar.jpg"
  twitter = "kojihigasa"

[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
  url = "/about"
[[menu.main]]
  weight = 3
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
  url = "/categories"
[[menu.main]]
  weight = 4
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
  url = "/tags"
[[menu.main]]
  weight = 5
  identifier = "search"
  name = "Search"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-search\"></i>"
  url = "/search"
  class = "st-search-show-outputs"
[[menu.main]]
  weight = 6
  identifier = "archives"
  name = "Archives"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
  url = "/archives"
[[menu.main]]
  weight = 7
  identifier = "contact"
  name = "Contact"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-envelope\"></i>"
  url = "/contact"

[[menu.links]]
  weight = 1
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/kHigasa"
[[menu.links]]
  weight = 2
  identifier = "stackoverflow"
  name = "Stack Overflow"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-stack-overflow\"></i>"
  url = "https://stackoverflow.com/users/9315234/koji-higasa"
[[menu.links]]
  weight = 3
  identifier = "reddit"
  name = "Reddit"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-reddit\"></i>"
  url = "https://www.reddit.com/user/khigasa"
[[menu.links]]
  weight = 4
  identifier = "medium"
  name = "Medium"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-medium\"></i>"
  url = "https://medium.com/@khigasa"
[[menu.links]]
  weight = 5
  identifier = "quora"
  name = "Quora"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-quora\"></i>"
  url = "https://www.quora.com/profile/khigasa-Higasa-Koji"
[[menu.links]]
  weight = 6
  identifier = "twitter"
  name = "Twitter"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-twitter\"></i>"
  url = "https://twitter.com/kohgasa"
[[menu.links]]
  weight = 7
  identifier = "facebook"
  name = "Facebook"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-facebook\"></i>"
  url = "https://www.facebook.com/khigasa"
[[menu.links]]
  weight = 8
  identifier = "linkedin"
  name = "LinkedIn"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-linkedin\"></i>"
  url = "https://www.linkedin.com/in/koji-higasa-21a83a171/"
[[menu.links]]
  weight = 9
  identifier = "instagram"
  name = "Instagram"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-instagram\"></i>"
  url = "https://www.instagram.com/khigasa/"
[[menu.links]]
  weight = 10
  identifier = "youtube"
  name = "YouTube"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-youtube\"></i>"
  url = "https://www.youtube.com/channel/UCskbXTbY517iXKpUzN2unUA"

[[menu.misc]]
  weight = 0
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
  url = "/index.xml"

[params]
  author = "kHigasa"
  description = "HHH Haggard Higs' Hacks - とある物理屋(になりたい人)の回想"
  sidebarBehavior = 1
  thumbnailImage = true
  thumbnailImagePosition = "right"
  autoThumbnailImage = true
  coverImage = "cover.jpg"
  imageGallery = true
  hierarchicalCategories = true
  syntaxHighlighter = 'highlight.js'
  clearReading = true
  wapPaginator = true

  [[params.sharingOptions]]
    name = "Facebook"
    icon = "fa-facebook-official"
    url = "https://www.facebook.com/sharer/sharer.php?u=%s"

  [[params.sharingOptions]]
    name = "Twitter"
    icon = "fa-twitter"
    url = "https://twitter.com/intent/tweet?text=%s"

[blackfriday]
  hrefTargetBlank = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
